services:
    db-pg:
        container_name: db-pg
        build: ./db_stuff
        env_file:
            - ./.env
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_NAME}
            PG_DATA: /var/lib/postgresql/data
        # healthcheck:
        #     test: 'exit 0'
        ports:
            - ${DB_PORT}:${DB_PORT}
        volumes:
            - pgdata:/var/lib/postgresql/data
        tty: true
        restart: on-failure
    server-app:
        container_name: server-app
        build:
            context: ./
            dockerfile: ./Dockerfile
            target: development
        command: sh -c 'npm run start'
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules
        env_file:
            - ./.env
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
            - ${DEBUG_PORT}:${DEBUG_PORT}
        depends_on:
            - db-pg
              # condition: service_healthy
        restart: on-failure

volumes:
    pgdata:
        driver: local
    server-app: {}
